# Generated by Django 5.2.5 on 2025-08-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, help_text='Enter an image URL'),
        ),
    ]
