# Generated by Django 5.2.5 on 2025-08-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(help_text='Enter a real image URL (e.g., from Google Images or Unsplash)'),
        ),
    ]
